// <auto-generated />
namespace Boulevard.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class addIcvBoulevardScore : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "202604070001000_addIcvBoulevardScore"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return null; }
        }
    }
}
